// AUTO-GENERATED by scripts/gen-color-matching-imports.mjs — do not edit by hand.
//
// Static image imports for the colour-matching illustration pack, so Next
// bundles all 47 photoreal frames into _next/static rather than serving
// them from public/.
//
// WHY THIS FILE EXISTS AT ALL
//
// This deployment does not serve apps/web/public. Measured, not assumed — see
// the identical note in data/illustration-images.ts and data/floor-images.ts,
// and F-131. A file sitting in public/images/color-matching/foo.webp 404s on
// the live site no matter how correctly it is committed.
//
// WHERE THE ALT TEXT AND CAPTIONS COME FROM
//
// scripts/fixtures/color-matching-manifest.csv — the brief every one of these
// 47 images was generated against. Copied here mechanically by the
// generator so the words rendered on the site cannot drift from that record.
// Regenerate with: node scripts/gen-color-matching-imports.mjs
//
// A static import also carries its own intrinsic width and height, so
// next/image reserves the correct box without a component having to declare it.
import type { StaticImageData } from 'next/image';

import case_forest_hill_walnut_uv from '../../public/images/case-studies/case-forest-hill-walnut-uv.webp';
import case_midtown_species_transition from '../../public/images/case-studies/case-midtown-species-transition.webp';
import cm_hub_guide_grid_identification from '../../public/images/color-matching/cm-hub-guide-grid-identification.webp';
import cm_hub_guide_grid_stairs from '../../public/images/color-matching/cm-hub-guide-grid-stairs.webp';
import cm_hub_hero_toronto_living_room from '../../public/images/color-matching/cm-hub-hero-toronto-living-room.webp';
import cm_hub_process_01_identify from '../../public/images/color-matching/cm-hub-process-01-identify.webp';
import cm_hub_process_02_sample_board from '../../public/images/color-matching/cm-hub-process-02-sample-board.webp';
import cm_hub_process_03_room_light from '../../public/images/color-matching/cm-hub-process-03-room-light.webp';
import cm_hub_process_04_honest_fail from '../../public/images/color-matching/cm-hub-process-04-honest-fail.webp';
import cm_hub_proof_forest_hill_walnut from '../../public/images/color-matching/cm-hub-proof-forest-hill-walnut.webp';
import cm_hub_proof_midtown_three_levels from '../../public/images/color-matching/cm-hub-proof-midtown-three-levels.webp';
import guide_door_hero_baseboard_meet from '../../public/images/guides/guide-door-hero-baseboard-meet.webp';
import guide_door_painted_undertone from '../../public/images/guides/guide-door-painted-undertone.webp';
import guide_door_threshold_contact from '../../public/images/guides/guide-door-threshold-contact.webp';
import guide_fail_hero_visible_patch from '../../public/images/guides/guide-fail-hero-visible-patch.webp';
import guide_fail_three_paths from '../../public/images/guides/guide-fail-three-paths.webp';
import guide_fail_wear_layer_measure from '../../public/images/guides/guide-fail-wear-layer-measure.webp';
import guide_id_ambering_oil from '../../public/images/guides/guide-id-ambering-oil.webp';
import guide_id_film_vs_penetrating from '../../public/images/guides/guide-id-film-vs-penetrating.webp';
import guide_id_hero_rug_reveal from '../../public/images/guides/guide-id-hero-rug-reveal.webp';
import guide_id_three_lights from '../../public/images/guides/guide-id-three-lights.webp';
import guide_newold_bad_butt_joint from '../../public/images/guides/guide-newold-bad-butt-joint.webp';
import guide_newold_feather_zone from '../../public/images/guides/guide-newold-feather-zone.webp';
import guide_newold_hero_invisible_weave from '../../public/images/guides/guide-newold-hero-invisible-weave.webp';
import guide_newold_threshold_strip from '../../public/images/guides/guide-newold-threshold-strip.webp';
import guide_signoff_day_vs_night from '../../public/images/guides/guide-signoff-day-vs-night.webp';
import guide_signoff_hero_condo_light from '../../public/images/guides/guide-signoff-hero-condo-light.webp';
import guide_signoff_written from '../../public/images/guides/guide-signoff-written.webp';
import guide_stain_hero_chip_vs_aged from '../../public/images/guides/guide-stain-hero-chip-vs-aged.webp';
import guide_stain_same_formula_two_species from '../../public/images/guides/guide-stain-same-formula-two-species.webp';
import guide_stain_sample_on_floor from '../../public/images/guides/guide-stain-sample-on-floor.webp';
import guide_stain_sheen_matte_vs_satin from '../../public/images/guides/guide-stain-sheen-matte-vs-satin.webp';
import guide_stair_hero_one_flight from '../../public/images/guides/guide-stair-hero-one-flight.webp';
import guide_stair_painted_vs_stained from '../../public/images/guides/guide-stair-painted-vs-stained.webp';
import guide_stair_sample_at_nosing from '../../public/images/guides/guide-stair-sample-at-nosing.webp';
import guide_stair_wear_shift from '../../public/images/guides/guide-stair-wear-shift.webp';
import service_refinish_bare_to_stained from '../../public/images/services/service-refinish-bare-to-stained.webp';
import service_restoration_before_after from '../../public/images/services/service-restoration-before-after.webp';
import service_restoration_hero_feather from '../../public/images/services/service-restoration-hero-feather.webp';
import service_stairs_matched_flight from '../../public/images/services/service-stairs-matched-flight.webp';
import species_black_walnut_undertone from '../../public/images/species/species-black-walnut-undertone.webp';
import species_hard_maple_undertone from '../../public/images/species/species-hard-maple-undertone.webp';
import species_hickory_undertone from '../../public/images/species/species-hickory-undertone.webp';
import species_red_oak_undertone from '../../public/images/species/species-red-oak-undertone.webp';
import species_same_stain_six_species from '../../public/images/species/species-same-stain-six-species.webp';
import species_white_ash_undertone from '../../public/images/species/species-white-ash-undertone.webp';
import species_white_oak_undertone from '../../public/images/species/species-white-oak-undertone.webp';

export type ColorMatchMeta = {
  /** public/images/<folder>/<id>.webp */
  folder: string;
  width: number;
  height: number;
  /** Describes the INFORMATION, not the picture. From MANIFEST.csv. */
  alt: string;
  /** Shown under the figure. From MANIFEST.csv. */
  caption: string;
  /** MANIFEST.csv's declared primary home for this frame. */
  pageUrl: string;
  section: string;
};

export const COLOR_MATCHING_IMAGES: Record<string, StaticImageData> = {
  'case-forest-hill-walnut-uv': case_forest_hill_walnut_uv,
  'case-midtown-species-transition': case_midtown_species_transition,
  'cm-hub-guide-grid-identification': cm_hub_guide_grid_identification,
  'cm-hub-guide-grid-stairs': cm_hub_guide_grid_stairs,
  'cm-hub-hero-toronto-living-room': cm_hub_hero_toronto_living_room,
  'cm-hub-process-01-identify': cm_hub_process_01_identify,
  'cm-hub-process-02-sample-board': cm_hub_process_02_sample_board,
  'cm-hub-process-03-room-light': cm_hub_process_03_room_light,
  'cm-hub-process-04-honest-fail': cm_hub_process_04_honest_fail,
  'cm-hub-proof-forest-hill-walnut': cm_hub_proof_forest_hill_walnut,
  'cm-hub-proof-midtown-three-levels': cm_hub_proof_midtown_three_levels,
  'guide-door-hero-baseboard-meet': guide_door_hero_baseboard_meet,
  'guide-door-painted-undertone': guide_door_painted_undertone,
  'guide-door-threshold-contact': guide_door_threshold_contact,
  'guide-fail-hero-visible-patch': guide_fail_hero_visible_patch,
  'guide-fail-three-paths': guide_fail_three_paths,
  'guide-fail-wear-layer-measure': guide_fail_wear_layer_measure,
  'guide-id-ambering-oil': guide_id_ambering_oil,
  'guide-id-film-vs-penetrating': guide_id_film_vs_penetrating,
  'guide-id-hero-rug-reveal': guide_id_hero_rug_reveal,
  'guide-id-three-lights': guide_id_three_lights,
  'guide-newold-bad-butt-joint': guide_newold_bad_butt_joint,
  'guide-newold-feather-zone': guide_newold_feather_zone,
  'guide-newold-hero-invisible-weave': guide_newold_hero_invisible_weave,
  'guide-newold-threshold-strip': guide_newold_threshold_strip,
  'guide-signoff-day-vs-night': guide_signoff_day_vs_night,
  'guide-signoff-hero-condo-light': guide_signoff_hero_condo_light,
  'guide-signoff-written': guide_signoff_written,
  'guide-stain-hero-chip-vs-aged': guide_stain_hero_chip_vs_aged,
  'guide-stain-same-formula-two-species': guide_stain_same_formula_two_species,
  'guide-stain-sample-on-floor': guide_stain_sample_on_floor,
  'guide-stain-sheen-matte-vs-satin': guide_stain_sheen_matte_vs_satin,
  'guide-stair-hero-one-flight': guide_stair_hero_one_flight,
  'guide-stair-painted-vs-stained': guide_stair_painted_vs_stained,
  'guide-stair-sample-at-nosing': guide_stair_sample_at_nosing,
  'guide-stair-wear-shift': guide_stair_wear_shift,
  'service-refinish-bare-to-stained': service_refinish_bare_to_stained,
  'service-restoration-before-after': service_restoration_before_after,
  'service-restoration-hero-feather': service_restoration_hero_feather,
  'service-stairs-matched-flight': service_stairs_matched_flight,
  'species-black-walnut-undertone': species_black_walnut_undertone,
  'species-hard-maple-undertone': species_hard_maple_undertone,
  'species-hickory-undertone': species_hickory_undertone,
  'species-red-oak-undertone': species_red_oak_undertone,
  'species-same-stain-six-species': species_same_stain_six_species,
  'species-white-ash-undertone': species_white_ash_undertone,
  'species-white-oak-undertone': species_white_oak_undertone,
};

export const COLOR_MATCHING_META: Record<string, ColorMatchMeta> = {
  'case-forest-hill-walnut-uv': {
    folder: 'case-studies',
    width: 3840,
    height: 2160,
    alt: 'Walnut wide plank in a Forest Hill room with south glass, even tone after UV-aware finishing',
    caption: 'Wide walnut held even under south light.',
    pageUrl: 'https://ecowoods.ca/case-studies/forest-hill-walnut-wide-plank-color-stability',
    section: 'hero',
  },
  'case-midtown-species-transition': {
    folder: 'case-studies',
    width: 3840,
    height: 2160,
    alt: 'Maple field, warmer oak level beyond, white oak stair and walnut stringer reading as one house',
    caption: 'Three-level transition across species, coordinated not identical.',
    pageUrl: 'https://ecowoods.ca/case-studies/midtown-townhouse-three-level-transition',
    section: 'hero',
  },
  'cm-hub-guide-grid-identification': {
    folder: 'color-matching',
    width: 2400,
    height: 1800,
    alt: 'Macro of a worn stair nosing where a thin polyurethane film is lifting from the wood',
    caption: 'Film finish versus wood — identification starts at a worn edge.',
    pageUrl: 'https://ecowoods.ca/guides/color-identification-existing-hardwood-finish',
    section: 'hub card for colour identification guide',
  },
  'cm-hub-guide-grid-stairs': {
    folder: 'color-matching',
    width: 2400,
    height: 1800,
    alt: 'Open stair with stained oak treads, darker walnut stringer and field floor beyond',
    caption: 'Stairs, railings and trim are a separate discipline from matching two floor boards.',
    pageUrl: 'https://ecowoods.ca/guides/stair-railing-trim-color-matching-toronto',
    section: 'hub card for stair railing trim guide',
  },
  'cm-hub-hero-toronto-living-room': {
    folder: 'color-matching',
    width: 3840,
    height: 2160,
    alt: 'Toronto midtown living room with continuous satin white oak floor running onto a stair, late afternoon window light and warm LEDs',
    caption: 'Floor, landing and first treads reading as one colour — process, not a promise.',
    pageUrl: 'https://ecowoods.ca/hardwood-color-matching-toronto',
    section: 'hero under H1',
  },
  'cm-hub-process-01-identify': {
    folder: 'color-matching',
    width: 2400,
    height: 1800,
    alt: 'Craftsman kneeling at a doorway threshold inspecting grain and a worn finish edge on existing 3-1/4 inch red oak strip, moisture meter on the floor',
    caption: 'Identify species, stain and finish type before anything is proposed.',
    pageUrl: 'https://ecowoods.ca/hardwood-color-matching-toronto',
    section: 'process step 1 Identify what is already there',
  },
  'cm-hub-process-02-sample-board': {
    folder: 'color-matching',
    width: 2400,
    height: 1800,
    alt: 'Cut-off of an actual floor board on a drop cloth with several small stain trial patches, rag, gloves and an unlabeled open stain can',
    caption: 'A cut-off of the actual board — never a generic chip.',
    pageUrl: 'https://ecowoods.ca/hardwood-color-matching-toronto',
    section: 'process step 2 Build the sample against the real material',
  },
  'cm-hub-process-03-room-light': {
    folder: 'color-matching',
    width: 2400,
    height: 1800,
    alt: 'Sample board laid on an existing condo floor, half in south-window daylight and half under warm LED pot lights',
    caption: 'Toronto condo lighting mixes daylight and LED colour temperatures.',
    pageUrl: 'https://ecowoods.ca/hardwood-color-matching-toronto',
    section: 'process step 3 Sign off in your room, under your light',
  },
  'cm-hub-process-04-honest-fail': {
    folder: 'color-matching',
    width: 2400,
    height: 1800,
    alt: 'Mid-field patch on an aged Toronto hallway floor that still reads as a different colour after staining',
    caption: 'Sometimes a spot match cannot be made to disappear.',
    pageUrl: 'https://ecowoods.ca/hardwood-color-matching-toronto',
    section: 'process step 4 Say plainly when it will not work',
  },
  'cm-hub-proof-forest-hill-walnut': {
    folder: 'color-matching',
    width: 3840,
    height: 2160,
    alt: 'Wide black walnut planks in a bright Forest Hill room with natural chocolate-to-silver variation under daylight',
    caption: 'Natural walnut variation held even under daylight.',
    pageUrl: 'https://ecowoods.ca/hardwood-color-matching-toronto',
    section: 'Proof Forest Hill walnut',
  },
  'cm-hub-proof-midtown-three-levels': {
    folder: 'color-matching',
    width: 3840,
    height: 2160,
    alt: 'Looking up a Toronto townhouse stairwell so basement, main floor and upper landing read as one tone',
    caption: 'Three levels coordinated as one house.',
    pageUrl: 'https://ecowoods.ca/hardwood-color-matching-toronto',
    section: 'Proof Midtown three-level',
  },
  'guide-door-hero-baseboard-meet': {
    folder: 'guides',
    width: 3840,
    height: 2160,
    alt: 'Stained oak floor meeting a painted warm-white baseboard and a stained oak door jamb',
    caption: 'Doors and trim are coordinated with the floor, not forced to the same wood.',
    pageUrl: 'https://ecowoods.ca/guides/door-woodwork-finish-coordination-toronto',
    section: 'hero',
  },
  'guide-door-painted-undertone': {
    folder: 'guides',
    width: 2400,
    height: 1800,
    alt: 'Two rooms with cool-grey paint versus warm-cream paint against hardwood floors',
    caption: 'Wall paint undertone changes how the floor reads.',
    pageUrl: 'https://ecowoods.ca/guides/door-woodwork-finish-coordination-toronto',
    section: 'painted undertone',
  },
  'guide-door-threshold-contact': {
    folder: 'guides',
    width: 2400,
    height: 1800,
    alt: 'Door slab, frame and hardwood threshold composed as one line',
    caption: 'The meeting line is the coordination problem.',
    pageUrl: 'https://ecowoods.ca/guides/door-woodwork-finish-coordination-toronto',
    section: 'threshold contact',
  },
  'guide-fail-hero-visible-patch': {
    folder: 'guides',
    width: 3840,
    height: 2160,
    alt: 'Honest failed spot match in an old Toronto hallway, a lighter patch in the aged field',
    caption: 'When a spot match will not disappear, the next decision is full sand or replace.',
    pageUrl: 'https://ecowoods.ca/guides/when-color-match-fails-full-sand-vs-replace',
    section: 'hero',
  },
  'guide-fail-three-paths': {
    folder: 'guides',
    width: 3840,
    height: 2160,
    alt: 'Same hallway shown three ways: visible spot repair, full sand and restain, and full replace with new wide plank',
    caption: 'Three honest paths when a match cannot be made to work.',
    pageUrl: 'https://ecowoods.ca/guides/when-color-match-fails-full-sand-vs-replace',
    section: 'three paths',
  },
  'guide-fail-wear-layer-measure': {
    folder: 'guides',
    width: 2400,
    height: 1800,
    alt: 'Caliper measuring remaining wear layer at an exposed board edge in a doorway',
    caption: 'Remaining wear layer is the decision, not hope.',
    pageUrl: 'https://ecowoods.ca/guides/when-color-match-fails-full-sand-vs-replace',
    section: 'wear layer measure',
  },
  'guide-id-ambering-oil': {
    folder: 'guides',
    width: 2400,
    height: 1800,
    alt: 'Same red oak run with a honey-ambered UV-exposed area beside a cooler protected area',
    caption: 'An existing floor has aged under its finish for years; a new sample has not.',
    pageUrl: 'https://ecowoods.ca/guides/color-identification-existing-hardwood-finish',
    section: 'ambering',
  },
  'guide-id-film-vs-penetrating': {
    folder: 'guides',
    width: 2400,
    height: 1800,
    alt: 'Split of the same species: flaking film finish at a threshold on the left, penetrating oil sitting in the wood on the right',
    caption: 'Finish type has to be identified before a sample is mixed.',
    pageUrl: 'https://ecowoods.ca/guides/color-identification-existing-hardwood-finish',
    section: 'film vs penetrating',
  },
  'guide-id-hero-rug-reveal': {
    folder: 'guides',
    width: 3840,
    height: 2160,
    alt: 'Rug pulled back on an aged red oak floor showing a protected paler patch against the ambered exposed field',
    caption: 'UV and traffic change the colour that is already there.',
    pageUrl: 'https://ecowoods.ca/guides/color-identification-existing-hardwood-finish',
    section: 'hero',
  },
  'guide-id-three-lights': {
    folder: 'guides',
    width: 2400,
    height: 1800,
    alt: 'One stained board shown in three Toronto lights: south window, 3000K pots, and a windowless hall',
    caption: 'Colour is signed off in the room\'s actual light.',
    pageUrl: 'https://ecowoods.ca/guides/color-identification-existing-hardwood-finish',
    section: 'three lights',
  },
  'guide-newold-bad-butt-joint': {
    folder: 'guides',
    width: 2400,
    height: 1800,
    alt: 'New boards finished separately and butted to an old finish, leaving an obvious seam',
    caption: 'Finishing new boards off-site and butting them to old finish is a common failure.',
    pageUrl: 'https://ecowoods.ca/guides/matching-new-hardwood-to-old-toronto',
    section: 'failure mode butt joint',
  },
  'guide-newold-feather-zone': {
    folder: 'guides',
    width: 2400,
    height: 1800,
    alt: 'Overhead of a blending zone where new boards are feathered and finished in one pass with the old field',
    caption: 'One sanding and finishing pass across old and new.',
    pageUrl: 'https://ecowoods.ca/guides/matching-new-hardwood-to-old-toronto',
    section: 'feather zone',
  },
  'guide-newold-hero-invisible-weave': {
    folder: 'guides',
    width: 3840,
    height: 2160,
    alt: 'Mid-field repair woven into existing strip oak so the seam is hard to find',
    caption: 'Matching new boards into old starts with species, width and a sample on the real material.',
    pageUrl: 'https://ecowoods.ca/guides/matching-new-hardwood-to-old-toronto',
    section: 'hero',
  },
  'guide-newold-threshold-strip': {
    folder: 'guides',
    width: 2400,
    height: 1800,
    alt: 'Honest room-to-room reducer between an aged red oak floor and a newer white oak floor',
    caption: 'Not every room-to-room change should be forced into one colour.',
    pageUrl: 'https://ecowoods.ca/guides/matching-new-hardwood-to-old-toronto',
    section: 'threshold strip',
  },
  'guide-signoff-day-vs-night': {
    folder: 'guides',
    width: 3840,
    height: 2160,
    alt: 'The same sample board in the same room at 2pm daylight versus 8pm LED',
    caption: 'Condo lighting changes how a stain reads.',
    pageUrl: 'https://ecowoods.ca/guides/sample-boards-on-site-trials-sign-off',
    section: 'day vs night',
  },
  'guide-signoff-hero-condo-light': {
    folder: 'guides',
    width: 3840,
    height: 2160,
    alt: 'Sample board on a glass-walled Toronto condo floor in mixed daylight and LED pot lights',
    caption: 'Approval happens in the room, not in a workshop.',
    pageUrl: 'https://ecowoods.ca/guides/sample-boards-on-site-trials-sign-off',
    section: 'hero',
  },
  'guide-signoff-written': {
    folder: 'guides',
    width: 2400,
    height: 1800,
    alt: 'Sample taped in place while a craftsman and homeowner review it with a clipboard, no readable personal data',
    caption: 'Sign-off is a written check in the room the work is done in.',
    pageUrl: 'https://ecowoods.ca/guides/sample-boards-on-site-trials-sign-off',
    section: 'written sign-off',
  },
  'guide-stain-hero-chip-vs-aged': {
    folder: 'guides',
    width: 3840,
    height: 2160,
    alt: 'A factory stain chip sitting on a 15-year-old floor that does not match the chip',
    caption: 'A stain sample and an aged floor are two different colours by the time the job happens.',
    pageUrl: 'https://ecowoods.ca/guides/stain-matching-existing-hardwood-floor-toronto',
    section: 'hero',
  },
  'guide-stain-same-formula-two-species': {
    folder: 'guides',
    width: 2400,
    height: 1800,
    alt: 'The same stain on white oak versus red oak: white oak even and cooler, red oak open-grain and warmer',
    caption: 'Species changes how a stain actually looks.',
    pageUrl: 'https://ecowoods.ca/guides/stain-matching-existing-hardwood-floor-toronto',
    section: 'same formula two species',
  },
  'guide-stain-sample-on-floor': {
    folder: 'guides',
    width: 2400,
    height: 1800,
    alt: 'Scrap board stained and laid against the live floor in a Toronto condo living room',
    caption: 'The sample is built against the actual floor, in the actual room.',
    pageUrl: 'https://ecowoods.ca/guides/stain-matching-existing-hardwood-floor-toronto',
    section: 'sample on floor',
  },
  'guide-stain-sheen-matte-vs-satin': {
    folder: 'guides',
    width: 2400,
    height: 1800,
    alt: 'Same species boards in daylight, matte finish on the left reading flatter, satin on the right reading richer',
    caption: 'A sheen change can read as a colour change.',
    pageUrl: 'https://ecowoods.ca/guides/stain-matching-existing-hardwood-floor-toronto',
    section: 'sheen matte vs satin',
  },
  'guide-stair-hero-one-flight': {
    folder: 'guides',
    width: 3840,
    height: 2160,
    alt: 'Full stair flight colour-matched to the upper landing, treads risers and nosings clean',
    caption: 'The flight is checked against the landing it meets.',
    pageUrl: 'https://ecowoods.ca/guides/stair-railing-trim-color-matching-toronto',
    section: 'hero',
  },
  'guide-stair-painted-vs-stained': {
    folder: 'guides',
    width: 2400,
    height: 1800,
    alt: 'Painted white balusters with a stained oak handrail and stained oak treads',
    caption: 'Coordination, not wood-to-wood matching.',
    pageUrl: 'https://ecowoods.ca/guides/stair-railing-trim-color-matching-toronto',
    section: 'painted vs stained',
  },
  'guide-stair-sample-at-nosing': {
    folder: 'guides',
    width: 2400,
    height: 1800,
    alt: 'Sample board checked at a stair nosing against the field floor on the landing',
    caption: 'The sample sits at the nosing, not only in a workshop.',
    pageUrl: 'https://ecowoods.ca/guides/stair-railing-trim-color-matching-toronto',
    section: 'sample at nosing',
  },
  'guide-stair-wear-shift': {
    folder: 'guides',
    width: 2400,
    height: 1800,
    alt: 'High-wear tread centres slightly lighter than the protected floor field',
    caption: 'Traffic changes colour independently of stain formula.',
    pageUrl: 'https://ecowoods.ca/guides/stair-railing-trim-color-matching-toronto',
    section: 'wear shift',
  },
  'service-refinish-bare-to-stained': {
    folder: 'services',
    width: 3840,
    height: 2160,
    alt: 'Same room: sanded-to-bare maple on the left, stained satin waterborne on the right',
    caption: 'Sand to bare wood, then stain and finish.',
    pageUrl: 'https://ecowoods.ca/services/floor-refinishing',
    section: 'bare to stained',
  },
  'service-restoration-before-after': {
    folder: 'services',
    width: 3840,
    height: 2160,
    alt: 'Same room same angle: damaged field on the left, repaired refinished floor on the right',
    caption: 'The method: repair the field, then finish across old and new.',
    pageUrl: 'https://ecowoods.ca/services/floor-restoration',
    section: 'The method before after',
  },
  'service-restoration-hero-feather': {
    folder: 'services',
    width: 3840,
    height: 2160,
    alt: 'Heritage strip floor after woven replacement boards, repair hard to find',
    caption: 'Restoration is board replacement, feathering and colour matching.',
    pageUrl: 'https://ecowoods.ca/services/floor-restoration',
    section: 'hero',
  },
  'service-stairs-matched-flight': {
    folder: 'services',
    width: 3840,
    height: 2160,
    alt: 'Refinished stair colour-matched to the main floor it meets',
    caption: 'Stairs are quoted per tread and colour-matched on site.',
    pageUrl: 'https://ecowoods.ca/services/stair-refinishing',
    section: 'hero matched flight',
  },
  'species-black-walnut-undertone': {
    folder: 'species',
    width: 2000,
    height: 2000,
    alt: 'Black walnut board with chocolate-to-silver heartwood variation',
    caption: 'Black walnut: chocolate-to-silver heartwood, luxury depth.',
    pageUrl: 'https://ecowoods.ca/guides/species-undertone-guide-color-matching-toronto',
    section: 'black walnut board portrait',
  },
  'species-hard-maple-undertone': {
    folder: 'species',
    width: 2000,
    height: 2000,
    alt: 'Hard maple board, pale closed grain almost uniform',
    caption: 'Hard maple: pale, closed grain; blotch risk if stained raw.',
    pageUrl: 'https://ecowoods.ca/guides/species-undertone-guide-color-matching-toronto',
    section: 'hard maple board portrait',
  },
  'species-hickory-undertone': {
    folder: 'species',
    width: 2000,
    height: 2000,
    alt: 'Hickory board with wild sapwood and heartwood contrast on a single face',
    caption: 'Hickory: character contrast, not a defect.',
    pageUrl: 'https://ecowoods.ca/guides/species-undertone-guide-color-matching-toronto',
    section: 'hickory board portrait',
  },
  'species-red-oak-undertone': {
    folder: 'species',
    width: 2000,
    height: 2000,
    alt: 'Red oak board with open grain and pinker heritage undertone',
    caption: 'Red oak: open grain, pinker heritage Toronto floor.',
    pageUrl: 'https://ecowoods.ca/guides/species-undertone-guide-color-matching-toronto',
    section: 'red oak board portrait',
  },
  'species-same-stain-six-species': {
    folder: 'species',
    width: 2400,
    height: 1800,
    alt: 'One stain recipe across six species boards in a studio lineup, no typography',
    caption: 'The same formula does not produce the same colour on every species.',
    pageUrl: 'https://ecowoods.ca/guides/species-undertone-guide-color-matching-toronto',
    section: 'one stain six species',
  },
  'species-white-ash-undertone': {
    folder: 'species',
    width: 2000,
    height: 2000,
    alt: 'White ash board, pale with straighter open grain',
    caption: 'White ash: pale Scandinavian, straighter open grain.',
    pageUrl: 'https://ecowoods.ca/guides/species-undertone-guide-color-matching-toronto',
    section: 'white ash board portrait',
  },
  'species-white-oak-undertone': {
    folder: 'species',
    width: 2000,
    height: 2000,
    alt: 'Unstained lightly satin-finished white oak board with even pores and ray fleck',
    caption: 'White oak: even pores, calm, takes grey smoked or natural.',
    pageUrl: 'https://ecowoods.ca/guides/species-undertone-guide-color-matching-toronto',
    section: 'white oak board portrait',
  },
};

/** A static-imported frame, or undefined if `id` is not in the pack. */
export const colorMatchingImage = (id: string): StaticImageData | undefined =>
  COLOR_MATCHING_IMAGES[id];

/**
 * Build a FigureRotator slide from a colour-matching frame. `href` is the
 * caller's choice (a case study, a guide) — the manifest's own `pageUrl` is
 * this frame's PRIMARY home, not necessarily the link a given rotator wants,
 * so it is never defaulted here silently.
 */
export const colorMatchingSlide = (
  id: string,
  href?: string,
): { id: string; src: StaticImageData; alt: string; caption: string; href?: string; width: number; height: number } | undefined => {
  const img = COLOR_MATCHING_IMAGES[id];
  const meta = COLOR_MATCHING_META[id];
  if (!img || !meta) return undefined;
  return { id, src: img, alt: meta.alt, caption: meta.caption, href, width: meta.width, height: meta.height };
};
