// AUTO-GENERATED by scripts/gen-illustration-imports.mjs — do not edit by hand.
//
// Static image imports, so Next bundles all 31 diagrams into
// _next/static rather than serving them from public/.
//
// WHY THIS FILE EXISTS AT ALL
//
// This deployment does not serve apps/web/public. Measured, not assumed:
// /qr-app.jpg — which lives in the REPO-ROOT public/ — returns 200, while
// /icon-192.png, which has sat in apps/web/public since long before any of this
// work, returns 404. So did every illustration written there.
//
// data/floor-images.ts and data/machine-images.ts already carry the same
// workaround and say so in their first line. 108 photographs render on the live
// site precisely because they are imported rather than served, and the 28
// diagrams were the only images on the site that were not.
//
// A static import also carries its own intrinsic width and height, so next/image
// reserves the correct box without the manifest having to declare it.
import type { StaticImageData } from 'next/image';

import concept_acclimation from '../../public/illustrations/concept-acclimation.webp';
import concept_edger_halo from '../../public/illustrations/concept-edger-halo.webp';
import concept_expansion_gap from '../../public/illustrations/concept-expansion-gap.webp';
import concept_mc_differential from '../../public/illustrations/concept-mc-differential.webp';
import failure_buckling from '../../public/illustrations/failure-buckling.webp';
import failure_crowning from '../../public/illustrations/failure-crowning.webp';
import failure_cupping from '../../public/illustrations/failure-cupping.webp';
import failure_edge_peaking from '../../public/illustrations/failure-edge-peaking.webp';
import failure_gapping from '../../public/illustrations/failure-gapping.webp';
import framework_hero from '../../public/illustrations/framework-hero.webp';
import guide_evaluate_quote from '../../public/illustrations/guide-evaluate-quote.webp';
import guide_method from '../../public/illustrations/guide-method.webp';
import guide_ref_condo from '../../public/illustrations/guide-ref-condo.webp';
import guide_ref_radiant from '../../public/illustrations/guide-ref-radiant.webp';
import guide_ref_refinish from '../../public/illustrations/guide-ref-refinish.webp';
import guide_solid_vs_engineered from '../../public/illustrations/guide-solid-vs-engineered.webp';
import og_data from '../../public/illustrations/og-data.webp';
import og_framework from '../../public/illustrations/og-framework.webp';
import og_glossary from '../../public/illustrations/og-glossary.webp';
import og_market from '../../public/illustrations/og-market.webp';
import og_standards from '../../public/illustrations/og-standards.webp';
import paper_climate from '../../public/illustrations/paper-climate.webp';
import paper_craft from '../../public/illustrations/paper-craft.webp';
import paper_selection from '../../public/illustrations/paper-selection.webp';
import pillar_accountability from '../../public/illustrations/pillar-accountability.webp';
import pillar_containment from '../../public/illustrations/pillar-containment.webp';
import pillar_moisture from '../../public/illustrations/pillar-moisture.webp';
import pillar_movement from '../../public/illustrations/pillar-movement.webp';
import pillar_specification from '../../public/illustrations/pillar-specification.webp';
import pillar_substrate from '../../public/illustrations/pillar-substrate.webp';
import resources_hero from '../../public/illustrations/resources-hero.webp';

export const ILLUSTRATION_IMAGES: Record<string, StaticImageData> = {
  'concept-acclimation': concept_acclimation,
  'concept-edger-halo': concept_edger_halo,
  'concept-expansion-gap': concept_expansion_gap,
  'concept-mc-differential': concept_mc_differential,
  'failure-buckling': failure_buckling,
  'failure-crowning': failure_crowning,
  'failure-cupping': failure_cupping,
  'failure-edge-peaking': failure_edge_peaking,
  'failure-gapping': failure_gapping,
  'framework-hero': framework_hero,
  'guide-evaluate-quote': guide_evaluate_quote,
  'guide-method': guide_method,
  'guide-ref-condo': guide_ref_condo,
  'guide-ref-radiant': guide_ref_radiant,
  'guide-ref-refinish': guide_ref_refinish,
  'guide-solid-vs-engineered': guide_solid_vs_engineered,
  'og-data': og_data,
  'og-framework': og_framework,
  'og-glossary': og_glossary,
  'og-market': og_market,
  'og-standards': og_standards,
  'paper-climate': paper_climate,
  'paper-craft': paper_craft,
  'paper-selection': paper_selection,
  'pillar-accountability': pillar_accountability,
  'pillar-containment': pillar_containment,
  'pillar-moisture': pillar_moisture,
  'pillar-movement': pillar_movement,
  'pillar-specification': pillar_specification,
  'pillar-substrate': pillar_substrate,
  'resources-hero': resources_hero,
};

export const illustrationImage = (id: string): StaticImageData | undefined =>
  ILLUSTRATION_IMAGES[id];
