// AUTO-GENERATED by scripts/gen-illustration-imports.mjs — do not edit by hand.
//
// Static image imports, so Next bundles all 118 diagrams into
// _next/static rather than serving them from public/.
//
// WHY THIS FILE EXISTS AT ALL
//
// This deployment does not serve apps/web/public. Measured, not assumed:
// /qr-app.jpg — which lives in the REPO-ROOT public/ — returns 200, while
// /icon-192.png, which has sat in apps/web/public since long before any of this
// work, returns 404. So did every illustration written there.
//
// data/floor-images.ts and data/machine-images.ts already carry the same
// workaround and say so in their first line. 108 photographs render on the live
// site precisely because they are imported rather than served, and the 28
// diagrams were the only images on the site that were not.
//
// A static import also carries its own intrinsic width and height, so next/image
// reserves the correct box without the manifest having to declare it.
import type { StaticImageData } from 'next/image';

import acoustic_three_methods from '../../public/illustrations/acoustic-three-methods.webp';
import acoustic_three_methods_b from '../../public/illustrations/acoustic-three-methods-b.webp';
import assembly_condo_slab_stack from '../../public/illustrations/assembly-condo-slab-stack.webp';
import assembly_condo_slab_stack_b from '../../public/illustrations/assembly-condo-slab-stack-b.webp';
import change_order_drift from '../../public/illustrations/change-order-drift.webp';
import change_order_drift_b from '../../public/illustrations/change-order-drift-b.webp';
import concept_acclimation from '../../public/illustrations/concept-acclimation.webp';
import concept_acclimation_72h from '../../public/illustrations/concept-acclimation-72h.webp';
import concept_acclimation_72h_b from '../../public/illustrations/concept-acclimation-72h-b.webp';
import concept_document_set from '../../public/illustrations/concept-document-set.webp';
import concept_document_set_b from '../../public/illustrations/concept-document-set-b.webp';
import concept_edger_halo from '../../public/illustrations/concept-edger-halo.webp';
import concept_expansion_gap from '../../public/illustrations/concept-expansion-gap.webp';
import concept_mc_differential from '../../public/illustrations/concept-mc-differential.webp';
import depth_three_refinishing_services from '../../public/illustrations/depth-three-refinishing-services.webp';
import depth_three_refinishing_services_b from '../../public/illustrations/depth-three-refinishing-services-b.webp';
import failure_buckling from '../../public/illustrations/failure-buckling.webp';
import failure_crowning from '../../public/illustrations/failure-crowning.webp';
import failure_cupping from '../../public/illustrations/failure-cupping.webp';
import failure_edge_peaking from '../../public/illustrations/failure-edge-peaking.webp';
import failure_gapping from '../../public/illustrations/failure-gapping.webp';
import fig_climate_rh_bands from '../../public/illustrations/fig-climate-rh-bands.webp';
import fig_failure_cascade from '../../public/illustrations/fig-failure-cascade.webp';
import fig_four_machines_roles from '../../public/illustrations/fig-four-machines-roles.webp';
import fig_full_sequence_timeline from '../../public/illustrations/fig-full-sequence-timeline.webp';
import fig_grit_progression from '../../public/illustrations/fig-grit-progression.webp';
import fig_installed_cost_bands from '../../public/illustrations/fig-installed-cost-bands.webp';
import fig_method_substrate_matrix from '../../public/illustrations/fig-method-substrate-matrix.webp';
import fig_moisture_testing_sequence from '../../public/illustrations/fig-moisture-testing-sequence.webp';
import fig_planetary_blend from '../../public/illustrations/fig-planetary-blend.webp';
import fig_protocol_gates from '../../public/illustrations/fig-protocol-gates.webp';
import fig_screening_between_coats from '../../public/illustrations/fig-screening-between-coats.webp';
import fig_species_janka from '../../public/illustrations/fig-species-janka.webp';
import framework_hero from '../../public/illustrations/framework-hero.webp';
import gap_midfield_obstructions from '../../public/illustrations/gap-midfield-obstructions.webp';
import gap_midfield_obstructions_b from '../../public/illustrations/gap-midfield-obstructions-b.webp';
import guide_choose_contractor from '../../public/illustrations/guide-choose-contractor.webp';
import guide_cost_toronto from '../../public/illustrations/guide-cost-toronto.webp';
import guide_dustless from '../../public/illustrations/guide-dustless.webp';
import guide_evaluate_quote from '../../public/illustrations/guide-evaluate-quote.webp';
import guide_herringbone_parquet from '../../public/illustrations/guide-herringbone-parquet.webp';
import guide_method from '../../public/illustrations/guide-method.webp';
import guide_ref_condo from '../../public/illustrations/guide-ref-condo.webp';
import guide_ref_radiant from '../../public/illustrations/guide-ref-radiant.webp';
import guide_ref_refinish from '../../public/illustrations/guide-ref-refinish.webp';
import guide_solid_vs_engineered from '../../public/illustrations/guide-solid-vs-engineered.webp';
import guide_white_oak from '../../public/illustrations/guide-white-oak.webp';
import machine_belt_drum_section from '../../public/illustrations/machine-belt-drum-section.webp';
import machine_belt_drum_section_b from '../../public/illustrations/machine-belt-drum-section-b.webp';
import machine_edger_reach from '../../public/illustrations/machine-edger-reach.webp';
import machine_edger_reach_b from '../../public/illustrations/machine-edger-reach-b.webp';
import machine_footprints_to_scale from '../../public/illustrations/machine-footprints-to-scale.webp';
import machine_footprints_to_scale_b from '../../public/illustrations/machine-footprints-to-scale-b.webp';
import machine_planetary_rotation from '../../public/illustrations/machine-planetary-rotation.webp';
import machine_planetary_rotation_b from '../../public/illustrations/machine-planetary-rotation-b.webp';
import map_service_areas_gta from '../../public/illustrations/map-service-areas-gta.webp';
import map_service_areas_gta_b from '../../public/illustrations/map-service-areas-gta-b.webp';
import og_about from '../../public/illustrations/og-about.webp';
import og_data from '../../public/illustrations/og-data.webp';
import og_framework from '../../public/illustrations/og-framework.webp';
import og_glossary from '../../public/illustrations/og-glossary.webp';
import og_market from '../../public/illustrations/og-market.webp';
import og_press from '../../public/illustrations/og-press.webp';
import og_reviews from '../../public/illustrations/og-reviews.webp';
import og_services from '../../public/illustrations/og-services.webp';
import og_standards from '../../public/illustrations/og-standards.webp';
import paper_climate from '../../public/illustrations/paper-climate.webp';
import paper_craft from '../../public/illustrations/paper-craft.webp';
import paper_selection from '../../public/illustrations/paper-selection.webp';
import pattern_layout_three from '../../public/illustrations/pattern-layout-three.webp';
import pattern_layout_three_b from '../../public/illustrations/pattern-layout-three-b.webp';
import pillar_accountability from '../../public/illustrations/pillar-accountability.webp';
import pillar_containment from '../../public/illustrations/pillar-containment.webp';
import pillar_moisture from '../../public/illustrations/pillar-moisture.webp';
import pillar_movement from '../../public/illustrations/pillar-movement.webp';
import pillar_specification from '../../public/illustrations/pillar-specification.webp';
import pillar_substrate from '../../public/illustrations/pillar-substrate.webp';
import price_bands_to_scale from '../../public/illustrations/price-bands-to-scale.webp';
import price_bands_to_scale_b from '../../public/illustrations/price-bands-to-scale-b.webp';
import protocol_timeline_install from '../../public/illustrations/protocol-timeline-install.webp';
import protocol_timeline_install_b from '../../public/illustrations/protocol-timeline-install-b.webp';
import radiant_failure_delay from '../../public/illustrations/radiant-failure-delay.webp';
import radiant_failure_delay_b from '../../public/illustrations/radiant-failure-delay-b.webp';
import resources_hero from '../../public/illustrations/resources-hero.webp';
import service_dust_free from '../../public/illustrations/service-dust-free.webp';
import service_inlays from '../../public/illustrations/service-inlays.webp';
import service_installation from '../../public/illustrations/service-installation.webp';
import service_refinishing from '../../public/illustrations/service-refinishing.webp';
import service_restoration from '../../public/illustrations/service-restoration.webp';
import service_stairs from '../../public/illustrations/service-stairs.webp';
import stairs_anatomy from '../../public/illustrations/stairs-anatomy.webp';
import stairs_anatomy_b from '../../public/illustrations/stairs-anatomy-b.webp';
import stairs_four_jobs from '../../public/illustrations/stairs-four-jobs.webp';
import stairs_four_jobs_b from '../../public/illustrations/stairs-four-jobs-b.webp';
import stairs_labour_vs_area from '../../public/illustrations/stairs-labour-vs-area.webp';
import stairs_labour_vs_area_b from '../../public/illustrations/stairs-labour-vs-area-b.webp';
import stairs_tread_vs_cap from '../../public/illustrations/stairs-tread-vs-cap.webp';
import stairs_tread_vs_cap_b from '../../public/illustrations/stairs-tread-vs-cap-b.webp';
import symptom_cause_tree from '../../public/illustrations/symptom-cause-tree.webp';
import symptom_cause_tree_b from '../../public/illustrations/symptom-cause-tree-b.webp';
import term_anisotropic from '../../public/illustrations/term-anisotropic.webp';
import term_cross_ply_core from '../../public/illustrations/term-cross-ply-core.webp';
import term_engineered from '../../public/illustrations/term-engineered.webp';
import term_floating from '../../public/illustrations/term-floating.webp';
import term_glue_down from '../../public/illustrations/term-glue-down.webp';
import term_hepa_containment from '../../public/illustrations/term-hepa-containment.webp';
import term_intercoat_screening from '../../public/illustrations/term-intercoat-screening.webp';
import term_janka from '../../public/illustrations/term-janka.webp';
import term_nail_down from '../../public/illustrations/term-nail-down.webp';
import term_planetary_sander from '../../public/illustrations/term-planetary-sander.webp';
import term_progressive_grits from '../../public/illustrations/term-progressive-grits.webp';
import term_radiant_heat from '../../public/illustrations/term-radiant-heat.webp';
import term_solid_hardwood from '../../public/illustrations/term-solid-hardwood.webp';
import term_subfloor from '../../public/illustrations/term-subfloor.webp';
import term_wear_layer from '../../public/illustrations/term-wear-layer.webp';
import term_white_oak from '../../public/illustrations/term-white-oak.webp';
import wear_layer_refinish_budget from '../../public/illustrations/wear-layer-refinish-budget.webp';
import wear_layer_refinish_budget_b from '../../public/illustrations/wear-layer-refinish-budget-b.webp';

export const ILLUSTRATION_IMAGES: Record<string, StaticImageData> = {
  'acoustic-three-methods': acoustic_three_methods,
  'acoustic-three-methods-b': acoustic_three_methods_b,
  'assembly-condo-slab-stack': assembly_condo_slab_stack,
  'assembly-condo-slab-stack-b': assembly_condo_slab_stack_b,
  'change-order-drift': change_order_drift,
  'change-order-drift-b': change_order_drift_b,
  'concept-acclimation': concept_acclimation,
  'concept-acclimation-72h': concept_acclimation_72h,
  'concept-acclimation-72h-b': concept_acclimation_72h_b,
  'concept-document-set': concept_document_set,
  'concept-document-set-b': concept_document_set_b,
  'concept-edger-halo': concept_edger_halo,
  'concept-expansion-gap': concept_expansion_gap,
  'concept-mc-differential': concept_mc_differential,
  'depth-three-refinishing-services': depth_three_refinishing_services,
  'depth-three-refinishing-services-b': depth_three_refinishing_services_b,
  'failure-buckling': failure_buckling,
  'failure-crowning': failure_crowning,
  'failure-cupping': failure_cupping,
  'failure-edge-peaking': failure_edge_peaking,
  'failure-gapping': failure_gapping,
  'fig-climate-rh-bands': fig_climate_rh_bands,
  'fig-failure-cascade': fig_failure_cascade,
  'fig-four-machines-roles': fig_four_machines_roles,
  'fig-full-sequence-timeline': fig_full_sequence_timeline,
  'fig-grit-progression': fig_grit_progression,
  'fig-installed-cost-bands': fig_installed_cost_bands,
  'fig-method-substrate-matrix': fig_method_substrate_matrix,
  'fig-moisture-testing-sequence': fig_moisture_testing_sequence,
  'fig-planetary-blend': fig_planetary_blend,
  'fig-protocol-gates': fig_protocol_gates,
  'fig-screening-between-coats': fig_screening_between_coats,
  'fig-species-janka': fig_species_janka,
  'framework-hero': framework_hero,
  'gap-midfield-obstructions': gap_midfield_obstructions,
  'gap-midfield-obstructions-b': gap_midfield_obstructions_b,
  'guide-choose-contractor': guide_choose_contractor,
  'guide-cost-toronto': guide_cost_toronto,
  'guide-dustless': guide_dustless,
  'guide-evaluate-quote': guide_evaluate_quote,
  'guide-herringbone-parquet': guide_herringbone_parquet,
  'guide-method': guide_method,
  'guide-ref-condo': guide_ref_condo,
  'guide-ref-radiant': guide_ref_radiant,
  'guide-ref-refinish': guide_ref_refinish,
  'guide-solid-vs-engineered': guide_solid_vs_engineered,
  'guide-white-oak': guide_white_oak,
  'machine-belt-drum-section': machine_belt_drum_section,
  'machine-belt-drum-section-b': machine_belt_drum_section_b,
  'machine-edger-reach': machine_edger_reach,
  'machine-edger-reach-b': machine_edger_reach_b,
  'machine-footprints-to-scale': machine_footprints_to_scale,
  'machine-footprints-to-scale-b': machine_footprints_to_scale_b,
  'machine-planetary-rotation': machine_planetary_rotation,
  'machine-planetary-rotation-b': machine_planetary_rotation_b,
  'map-service-areas-gta': map_service_areas_gta,
  'map-service-areas-gta-b': map_service_areas_gta_b,
  'og-about': og_about,
  'og-data': og_data,
  'og-framework': og_framework,
  'og-glossary': og_glossary,
  'og-market': og_market,
  'og-press': og_press,
  'og-reviews': og_reviews,
  'og-services': og_services,
  'og-standards': og_standards,
  'paper-climate': paper_climate,
  'paper-craft': paper_craft,
  'paper-selection': paper_selection,
  'pattern-layout-three': pattern_layout_three,
  'pattern-layout-three-b': pattern_layout_three_b,
  'pillar-accountability': pillar_accountability,
  'pillar-containment': pillar_containment,
  'pillar-moisture': pillar_moisture,
  'pillar-movement': pillar_movement,
  'pillar-specification': pillar_specification,
  'pillar-substrate': pillar_substrate,
  'price-bands-to-scale': price_bands_to_scale,
  'price-bands-to-scale-b': price_bands_to_scale_b,
  'protocol-timeline-install': protocol_timeline_install,
  'protocol-timeline-install-b': protocol_timeline_install_b,
  'radiant-failure-delay': radiant_failure_delay,
  'radiant-failure-delay-b': radiant_failure_delay_b,
  'resources-hero': resources_hero,
  'service-dust-free': service_dust_free,
  'service-inlays': service_inlays,
  'service-installation': service_installation,
  'service-refinishing': service_refinishing,
  'service-restoration': service_restoration,
  'service-stairs': service_stairs,
  'stairs-anatomy': stairs_anatomy,
  'stairs-anatomy-b': stairs_anatomy_b,
  'stairs-four-jobs': stairs_four_jobs,
  'stairs-four-jobs-b': stairs_four_jobs_b,
  'stairs-labour-vs-area': stairs_labour_vs_area,
  'stairs-labour-vs-area-b': stairs_labour_vs_area_b,
  'stairs-tread-vs-cap': stairs_tread_vs_cap,
  'stairs-tread-vs-cap-b': stairs_tread_vs_cap_b,
  'symptom-cause-tree': symptom_cause_tree,
  'symptom-cause-tree-b': symptom_cause_tree_b,
  'term-anisotropic': term_anisotropic,
  'term-cross-ply-core': term_cross_ply_core,
  'term-engineered': term_engineered,
  'term-floating': term_floating,
  'term-glue-down': term_glue_down,
  'term-hepa-containment': term_hepa_containment,
  'term-intercoat-screening': term_intercoat_screening,
  'term-janka': term_janka,
  'term-nail-down': term_nail_down,
  'term-planetary-sander': term_planetary_sander,
  'term-progressive-grits': term_progressive_grits,
  'term-radiant-heat': term_radiant_heat,
  'term-solid-hardwood': term_solid_hardwood,
  'term-subfloor': term_subfloor,
  'term-wear-layer': term_wear_layer,
  'term-white-oak': term_white_oak,
  'wear-layer-refinish-budget': wear_layer_refinish_budget,
  'wear-layer-refinish-budget-b': wear_layer_refinish_budget_b,
};

export const illustrationImage = (id: string): StaticImageData | undefined =>
  ILLUSTRATION_IMAGES[id];
