// AUTO-GENERATED by scripts/gen-slider-imports.mjs — do not edit by hand.
//
// Static imports for every before/after frame, so Next bundles them into
// _next/static instead of serving them from public/.
//
// THIS DEPLOYMENT DOES NOT SERVE apps/web/public. Measured, not assumed —
// audit/FINDINGS.md F-131. A URL like /images/sliders/01-...-after.webp is a
// 404 here no matter how correctly the file is committed. Both slider briefs
// specify exactly those URLs; this file is why the sliders render anyway.
//
// A static import also carries its own intrinsic width and height, so
// next/image reserves the right box and the two frames of a pair cannot
// disagree about their size without TypeScript noticing.
import type { StaticImageData } from 'next/image';

import f_01_richmond_hill_maple_condo_after from '../../public/images/sliders/01-richmond-hill-maple-condo-after.webp';
import f_01_richmond_hill_maple_condo_before from '../../public/images/sliders/01-richmond-hill-maple-condo-before.webp';
import f_02_forest_hill_walnut_wideplank_after from '../../public/images/sliders/02-forest-hill-walnut-wideplank-after.webp';
import f_02_forest_hill_walnut_wideplank_before from '../../public/images/sliders/02-forest-hill-walnut-wideplank-before.webp';
import f_03_yorkville_loft_moisture_after from '../../public/images/sliders/03-yorkville-loft-moisture-after.webp';
import f_03_yorkville_loft_moisture_before from '../../public/images/sliders/03-yorkville-loft-moisture-before.webp';
import f_04_rosedale_stairs_radiant_after from '../../public/images/sliders/04-rosedale-stairs-radiant-after.webp';
import f_04_rosedale_stairs_radiant_before from '../../public/images/sliders/04-rosedale-stairs-radiant-before.webp';
import f_05_midtown_townhouse_continuous_after from '../../public/images/sliders/05-midtown-townhouse-continuous-after.webp';
import f_05_midtown_townhouse_continuous_before from '../../public/images/sliders/05-midtown-townhouse-continuous-before.webp';
import f_06_richmond_hill_builder_oak_after from '../../public/images/sliders/06-richmond-hill-builder-oak-after.webp';
import f_06_richmond_hill_builder_oak_before from '../../public/images/sliders/06-richmond-hill-builder-oak-before.webp';
import f_07_dustfree_occupied_home_after from '../../public/images/sliders/07-dustfree-occupied-home-after.webp';
import f_07_dustfree_occupied_home_before from '../../public/images/sliders/07-dustfree-occupied-home-before.webp';
import f_08_herringbone_walnut_border_after from '../../public/images/sliders/08-herringbone-walnut-border-after.webp';
import f_08_herringbone_walnut_border_before from '../../public/images/sliders/08-herringbone-walnut-border-before.webp';
import f_09_distillery_whiteoak_slab_after from '../../public/images/sliders/09-distillery-whiteoak-slab-after.webp';
import f_09_distillery_whiteoak_slab_before from '../../public/images/sliders/09-distillery-whiteoak-slab-before.webp';
import f_10_kitchen_water_restoration_after from '../../public/images/sliders/10-kitchen-water-restoration-after.webp';
import f_10_kitchen_water_restoration_before from '../../public/images/sliders/10-kitchen-water-restoration-before.webp';
import f_11_occupied_living_refinish_after from '../../public/images/sliders/11-occupied-living-refinish-after.webp';
import f_11_occupied_living_refinish_before from '../../public/images/sliders/11-occupied-living-refinish-before.webp';
import f_12_kingwest_whiteoak_condo_after from '../../public/images/sliders/12-kingwest-whiteoak-condo-after.webp';
import f_12_kingwest_whiteoak_condo_before from '../../public/images/sliders/12-kingwest-whiteoak-condo-before.webp';
import f_13_medallion_walnut_maple_after from '../../public/images/sliders/13-medallion-walnut-maple-after.webp';
import f_13_medallion_walnut_maple_before from '../../public/images/sliders/13-medallion-walnut-maple-before.webp';
import f_14_radiant_maple_sunroom_after from '../../public/images/sliders/14-radiant-maple-sunroom-after.webp';
import f_14_radiant_maple_sunroom_before from '../../public/images/sliders/14-radiant-maple-sunroom-before.webp';
import f_15_condo_corridor_commercial_after from '../../public/images/sliders/15-condo-corridor-commercial-after.webp';
import f_15_condo_corridor_commercial_before from '../../public/images/sliders/15-condo-corridor-commercial-before.webp';
import f_16_heritage_baywindow_oak_after from '../../public/images/sliders/16-heritage-baywindow-oak-after.webp';
import f_16_heritage_baywindow_oak_before from '../../public/images/sliders/16-heritage-baywindow-oak-before.webp';
import f_custom_inlay_after from '../../public/proof/custom-inlay-after.webp';
import f_custom_inlay_before from '../../public/proof/custom-inlay-before.webp';
import f_distillery_loft_after from '../../public/proof/distillery-loft-after.webp';
import f_distillery_loft_before from '../../public/proof/distillery-loft-before.webp';
import f_dust_free_occupied_after from '../../public/proof/dust-free-occupied-after.webp';
import f_dust_free_occupied_during from '../../public/proof/dust-free-occupied-during.webp';
import f_forest_hill_walnut_after from '../../public/proof/forest-hill-walnut-after.webp';
import f_forest_hill_walnut_before from '../../public/proof/forest-hill-walnut-before.webp';
import f_herringbone_condo_after from '../../public/proof/herringbone-condo-after.webp';
import f_herringbone_condo_before from '../../public/proof/herringbone-condo-before.webp';
import f_midtown_townhouse_after from '../../public/proof/midtown-townhouse-after.webp';
import f_midtown_townhouse_before from '../../public/proof/midtown-townhouse-before.webp';
import f_problems_cupping_after from '../../public/proof/problems-cupping-after.webp';
import f_problems_cupping_before from '../../public/proof/problems-cupping-before.webp';
import f_realtor_prelist_after from '../../public/proof/realtor-prelist-after.webp';
import f_realtor_prelist_before from '../../public/proof/realtor-prelist-before.webp';
import f_restoration_water_after from '../../public/proof/restoration-water-after.webp';
import f_restoration_water_before from '../../public/proof/restoration-water-before.webp';
import f_richmond_hill_maple_after from '../../public/proof/richmond-hill-maple-after.webp';
import f_richmond_hill_maple_before from '../../public/proof/richmond-hill-maple-before.webp';
import f_rosedale_stairs_after from '../../public/proof/rosedale-stairs-after.webp';
import f_rosedale_stairs_before from '../../public/proof/rosedale-stairs-before.webp';
import f_screen_recoat_after from '../../public/proof/screen-recoat-after.webp';
import f_screen_recoat_before from '../../public/proof/screen-recoat-before.webp';
import f_yorkville_basement_after from '../../public/proof/yorkville-basement-after.webp';
import f_yorkville_basement_before from '../../public/proof/yorkville-basement-before.webp';

export const SLIDER_FRAMES: Record<string, StaticImageData> = {
  '01-richmond-hill-maple-condo-after': f_01_richmond_hill_maple_condo_after,
  '01-richmond-hill-maple-condo-before': f_01_richmond_hill_maple_condo_before,
  '02-forest-hill-walnut-wideplank-after': f_02_forest_hill_walnut_wideplank_after,
  '02-forest-hill-walnut-wideplank-before': f_02_forest_hill_walnut_wideplank_before,
  '03-yorkville-loft-moisture-after': f_03_yorkville_loft_moisture_after,
  '03-yorkville-loft-moisture-before': f_03_yorkville_loft_moisture_before,
  '04-rosedale-stairs-radiant-after': f_04_rosedale_stairs_radiant_after,
  '04-rosedale-stairs-radiant-before': f_04_rosedale_stairs_radiant_before,
  '05-midtown-townhouse-continuous-after': f_05_midtown_townhouse_continuous_after,
  '05-midtown-townhouse-continuous-before': f_05_midtown_townhouse_continuous_before,
  '06-richmond-hill-builder-oak-after': f_06_richmond_hill_builder_oak_after,
  '06-richmond-hill-builder-oak-before': f_06_richmond_hill_builder_oak_before,
  '07-dustfree-occupied-home-after': f_07_dustfree_occupied_home_after,
  '07-dustfree-occupied-home-before': f_07_dustfree_occupied_home_before,
  '08-herringbone-walnut-border-after': f_08_herringbone_walnut_border_after,
  '08-herringbone-walnut-border-before': f_08_herringbone_walnut_border_before,
  '09-distillery-whiteoak-slab-after': f_09_distillery_whiteoak_slab_after,
  '09-distillery-whiteoak-slab-before': f_09_distillery_whiteoak_slab_before,
  '10-kitchen-water-restoration-after': f_10_kitchen_water_restoration_after,
  '10-kitchen-water-restoration-before': f_10_kitchen_water_restoration_before,
  '11-occupied-living-refinish-after': f_11_occupied_living_refinish_after,
  '11-occupied-living-refinish-before': f_11_occupied_living_refinish_before,
  '12-kingwest-whiteoak-condo-after': f_12_kingwest_whiteoak_condo_after,
  '12-kingwest-whiteoak-condo-before': f_12_kingwest_whiteoak_condo_before,
  '13-medallion-walnut-maple-after': f_13_medallion_walnut_maple_after,
  '13-medallion-walnut-maple-before': f_13_medallion_walnut_maple_before,
  '14-radiant-maple-sunroom-after': f_14_radiant_maple_sunroom_after,
  '14-radiant-maple-sunroom-before': f_14_radiant_maple_sunroom_before,
  '15-condo-corridor-commercial-after': f_15_condo_corridor_commercial_after,
  '15-condo-corridor-commercial-before': f_15_condo_corridor_commercial_before,
  '16-heritage-baywindow-oak-after': f_16_heritage_baywindow_oak_after,
  '16-heritage-baywindow-oak-before': f_16_heritage_baywindow_oak_before,
  'custom-inlay-after': f_custom_inlay_after,
  'custom-inlay-before': f_custom_inlay_before,
  'distillery-loft-after': f_distillery_loft_after,
  'distillery-loft-before': f_distillery_loft_before,
  'dust-free-occupied-after': f_dust_free_occupied_after,
  'dust-free-occupied-during': f_dust_free_occupied_during,
  'forest-hill-walnut-after': f_forest_hill_walnut_after,
  'forest-hill-walnut-before': f_forest_hill_walnut_before,
  'herringbone-condo-after': f_herringbone_condo_after,
  'herringbone-condo-before': f_herringbone_condo_before,
  'midtown-townhouse-after': f_midtown_townhouse_after,
  'midtown-townhouse-before': f_midtown_townhouse_before,
  'problems-cupping-after': f_problems_cupping_after,
  'problems-cupping-before': f_problems_cupping_before,
  'realtor-prelist-after': f_realtor_prelist_after,
  'realtor-prelist-before': f_realtor_prelist_before,
  'restoration-water-after': f_restoration_water_after,
  'restoration-water-before': f_restoration_water_before,
  'richmond-hill-maple-after': f_richmond_hill_maple_after,
  'richmond-hill-maple-before': f_richmond_hill_maple_before,
  'rosedale-stairs-after': f_rosedale_stairs_after,
  'rosedale-stairs-before': f_rosedale_stairs_before,
  'screen-recoat-after': f_screen_recoat_after,
  'screen-recoat-before': f_screen_recoat_before,
  'yorkville-basement-after': f_yorkville_basement_after,
  'yorkville-basement-before': f_yorkville_basement_before,
};

export type SliderFrameKey = keyof typeof SLIDER_FRAMES;
