// AUTO-GENERATED by scripts/gen-trilogy-imports.mjs — do not edit by hand.
//
// Static image imports for the 20-trilogy photo set, so Next bundles all
// 60 frames into _next/static rather than serving them from public/.
//
// WHY THIS FILE EXISTS AT ALL
//
// This deployment does not serve apps/web/public. Measured, not assumed — see
// the identical note in data/illustration-images.ts, data/floor-images.ts and
// data/color-matching-images.ts, and F-131.
//
// A static import also carries its own intrinsic width and height on the
// imported object itself (StaticImageData.width / .height) — lib/trilogies.ts
// reads those directly rather than maintaining a second, driftable dims table.
//
// Regenerate with: node scripts/gen-trilogy-imports.mjs
import type { StaticImageData } from 'next/image';

import curved_oak_iron_balustrade_01 from '../../public/images/trilogies/curved-oak-iron-balustrade/01.webp';
import curved_oak_iron_balustrade_02 from '../../public/images/trilogies/curved-oak-iron-balustrade/02.webp';
import curved_oak_iron_balustrade_03 from '../../public/images/trilogies/curved-oak-iron-balustrade/03.webp';
import dark_oak_plank_living_01 from '../../public/images/trilogies/dark-oak-plank-living/01.webp';
import dark_oak_plank_living_02 from '../../public/images/trilogies/dark-oak-plank-living/02.webp';
import dark_oak_plank_living_03 from '../../public/images/trilogies/dark-oak-plank-living/03.webp';
import floral_medallion_inlay_01 from '../../public/images/trilogies/floral-medallion-inlay/01.webp';
import floral_medallion_inlay_02 from '../../public/images/trilogies/floral-medallion-inlay/02.webp';
import floral_medallion_inlay_03 from '../../public/images/trilogies/floral-medallion-inlay/03.webp';
import foyer_oak_treads_iron_01 from '../../public/images/trilogies/foyer-oak-treads-iron/01.webp';
import foyer_oak_treads_iron_02 from '../../public/images/trilogies/foyer-oak-treads-iron/02.webp';
import foyer_oak_treads_iron_03 from '../../public/images/trilogies/foyer-oak-treads-iron/03.webp';
import geometric_border_parquet_study_01 from '../../public/images/trilogies/geometric-border-parquet-study/01.webp';
import geometric_border_parquet_study_02 from '../../public/images/trilogies/geometric-border-parquet-study/02.webp';
import geometric_border_parquet_study_03 from '../../public/images/trilogies/geometric-border-parquet-study/03.webp';
import geometric_inlay_borders_01 from '../../public/images/trilogies/geometric-inlay-borders/01.webp';
import geometric_inlay_borders_02 from '../../public/images/trilogies/geometric-inlay-borders/02.webp';
import geometric_inlay_borders_03 from '../../public/images/trilogies/geometric-inlay-borders/03.webp';
import geometric_parquet_french_doors_01 from '../../public/images/trilogies/geometric-parquet-french-doors/01.webp';
import geometric_parquet_french_doors_02 from '../../public/images/trilogies/geometric-parquet-french-doors/02.webp';
import geometric_parquet_french_doors_03 from '../../public/images/trilogies/geometric-parquet-french-doors/03.webp';
import geometric_versailles_parquet_estate_01 from '../../public/images/trilogies/geometric-versailles-parquet-estate/01.webp';
import geometric_versailles_parquet_estate_02 from '../../public/images/trilogies/geometric-versailles-parquet-estate/02.webp';
import geometric_versailles_parquet_estate_03 from '../../public/images/trilogies/geometric-versailles-parquet-estate/03.webp';
import herringbone_dormer_room_01 from '../../public/images/trilogies/herringbone-dormer-room/01.webp';
import herringbone_dormer_room_02 from '../../public/images/trilogies/herringbone-dormer-room/02.webp';
import herringbone_dormer_room_03 from '../../public/images/trilogies/herringbone-dormer-room/03.webp';
import herringbone_oak_border_01 from '../../public/images/trilogies/herringbone-oak-border/01.webp';
import herringbone_oak_border_02 from '../../public/images/trilogies/herringbone-oak-border/02.webp';
import herringbone_oak_border_03 from '../../public/images/trilogies/herringbone-oak-border/03.webp';
import library_chevron_wide_band_parquet_01 from '../../public/images/trilogies/library-chevron-wide-band-parquet/01.webp';
import library_chevron_wide_band_parquet_02 from '../../public/images/trilogies/library-chevron-wide-band-parquet/02.webp';
import library_chevron_wide_band_parquet_03 from '../../public/images/trilogies/library-chevron-wide-band-parquet/03.webp';
import loft_kitchen_light_strip_01 from '../../public/images/trilogies/loft-kitchen-light-strip/01.webp';
import loft_kitchen_light_strip_02 from '../../public/images/trilogies/loft-kitchen-light-strip/02.webp';
import loft_kitchen_light_strip_03 from '../../public/images/trilogies/loft-kitchen-light-strip/03.webp';
import oak_hallway_closet_transition_01 from '../../public/images/trilogies/oak-hallway-closet-transition/01.webp';
import oak_hallway_closet_transition_02 from '../../public/images/trilogies/oak-hallway-closet-transition/02.webp';
import oak_hallway_closet_transition_03 from '../../public/images/trilogies/oak-hallway-closet-transition/03.webp';
import paneled_oval_room_herringbone_01 from '../../public/images/trilogies/paneled-oval-room-herringbone/01.webp';
import paneled_oval_room_herringbone_02 from '../../public/images/trilogies/paneled-oval-room-herringbone/02.webp';
import paneled_oval_room_herringbone_03 from '../../public/images/trilogies/paneled-oval-room-herringbone/03.webp';
import rickis_store_maple_strip_01 from '../../public/images/trilogies/rickis-store-maple-strip/01.webp';
import rickis_store_maple_strip_02 from '../../public/images/trilogies/rickis-store-maple-strip/02.webp';
import rickis_store_maple_strip_03 from '../../public/images/trilogies/rickis-store-maple-strip/03.webp';
import rickis_storefront_01 from '../../public/images/trilogies/rickis-storefront/01.webp';
import rickis_storefront_02 from '../../public/images/trilogies/rickis-storefront/02.webp';
import rickis_storefront_03 from '../../public/images/trilogies/rickis-storefront/03.webp';
import salon_dark_oak_chandelier_01 from '../../public/images/trilogies/salon-dark-oak-chandelier/01.webp';
import salon_dark_oak_chandelier_02 from '../../public/images/trilogies/salon-dark-oak-chandelier/02.webp';
import salon_dark_oak_chandelier_03 from '../../public/images/trilogies/salon-dark-oak-chandelier/03.webp';
import salon_fireplace_continuous_floor_01 from '../../public/images/trilogies/salon-fireplace-continuous-floor/01.webp';
import salon_fireplace_continuous_floor_02 from '../../public/images/trilogies/salon-fireplace-continuous-floor/02.webp';
import salon_fireplace_continuous_floor_03 from '../../public/images/trilogies/salon-fireplace-continuous-floor/03.webp';
import sculptural_handrail_curve_01 from '../../public/images/trilogies/sculptural-handrail-curve/01.webp';
import sculptural_handrail_curve_02 from '../../public/images/trilogies/sculptural-handrail-curve/02.webp';
import sculptural_handrail_curve_03 from '../../public/images/trilogies/sculptural-handrail-curve/03.webp';
import spiral_looking_down_01 from '../../public/images/trilogies/spiral-looking-down/01.webp';
import spiral_looking_down_02 from '../../public/images/trilogies/spiral-looking-down/02.webp';
import spiral_looking_down_03 from '../../public/images/trilogies/spiral-looking-down/03.webp';

export const TRILOGY_IMAGES: Record<string, StaticImageData> = {
  'curved-oak-iron-balustrade-01': curved_oak_iron_balustrade_01,
  'curved-oak-iron-balustrade-02': curved_oak_iron_balustrade_02,
  'curved-oak-iron-balustrade-03': curved_oak_iron_balustrade_03,
  'dark-oak-plank-living-01': dark_oak_plank_living_01,
  'dark-oak-plank-living-02': dark_oak_plank_living_02,
  'dark-oak-plank-living-03': dark_oak_plank_living_03,
  'floral-medallion-inlay-01': floral_medallion_inlay_01,
  'floral-medallion-inlay-02': floral_medallion_inlay_02,
  'floral-medallion-inlay-03': floral_medallion_inlay_03,
  'foyer-oak-treads-iron-01': foyer_oak_treads_iron_01,
  'foyer-oak-treads-iron-02': foyer_oak_treads_iron_02,
  'foyer-oak-treads-iron-03': foyer_oak_treads_iron_03,
  'geometric-border-parquet-study-01': geometric_border_parquet_study_01,
  'geometric-border-parquet-study-02': geometric_border_parquet_study_02,
  'geometric-border-parquet-study-03': geometric_border_parquet_study_03,
  'geometric-inlay-borders-01': geometric_inlay_borders_01,
  'geometric-inlay-borders-02': geometric_inlay_borders_02,
  'geometric-inlay-borders-03': geometric_inlay_borders_03,
  'geometric-parquet-french-doors-01': geometric_parquet_french_doors_01,
  'geometric-parquet-french-doors-02': geometric_parquet_french_doors_02,
  'geometric-parquet-french-doors-03': geometric_parquet_french_doors_03,
  'geometric-versailles-parquet-estate-01': geometric_versailles_parquet_estate_01,
  'geometric-versailles-parquet-estate-02': geometric_versailles_parquet_estate_02,
  'geometric-versailles-parquet-estate-03': geometric_versailles_parquet_estate_03,
  'herringbone-dormer-room-01': herringbone_dormer_room_01,
  'herringbone-dormer-room-02': herringbone_dormer_room_02,
  'herringbone-dormer-room-03': herringbone_dormer_room_03,
  'herringbone-oak-border-01': herringbone_oak_border_01,
  'herringbone-oak-border-02': herringbone_oak_border_02,
  'herringbone-oak-border-03': herringbone_oak_border_03,
  'library-chevron-wide-band-parquet-01': library_chevron_wide_band_parquet_01,
  'library-chevron-wide-band-parquet-02': library_chevron_wide_band_parquet_02,
  'library-chevron-wide-band-parquet-03': library_chevron_wide_band_parquet_03,
  'loft-kitchen-light-strip-01': loft_kitchen_light_strip_01,
  'loft-kitchen-light-strip-02': loft_kitchen_light_strip_02,
  'loft-kitchen-light-strip-03': loft_kitchen_light_strip_03,
  'oak-hallway-closet-transition-01': oak_hallway_closet_transition_01,
  'oak-hallway-closet-transition-02': oak_hallway_closet_transition_02,
  'oak-hallway-closet-transition-03': oak_hallway_closet_transition_03,
  'paneled-oval-room-herringbone-01': paneled_oval_room_herringbone_01,
  'paneled-oval-room-herringbone-02': paneled_oval_room_herringbone_02,
  'paneled-oval-room-herringbone-03': paneled_oval_room_herringbone_03,
  'rickis-store-maple-strip-01': rickis_store_maple_strip_01,
  'rickis-store-maple-strip-02': rickis_store_maple_strip_02,
  'rickis-store-maple-strip-03': rickis_store_maple_strip_03,
  'rickis-storefront-01': rickis_storefront_01,
  'rickis-storefront-02': rickis_storefront_02,
  'rickis-storefront-03': rickis_storefront_03,
  'salon-dark-oak-chandelier-01': salon_dark_oak_chandelier_01,
  'salon-dark-oak-chandelier-02': salon_dark_oak_chandelier_02,
  'salon-dark-oak-chandelier-03': salon_dark_oak_chandelier_03,
  'salon-fireplace-continuous-floor-01': salon_fireplace_continuous_floor_01,
  'salon-fireplace-continuous-floor-02': salon_fireplace_continuous_floor_02,
  'salon-fireplace-continuous-floor-03': salon_fireplace_continuous_floor_03,
  'sculptural-handrail-curve-01': sculptural_handrail_curve_01,
  'sculptural-handrail-curve-02': sculptural_handrail_curve_02,
  'sculptural-handrail-curve-03': sculptural_handrail_curve_03,
  'spiral-looking-down-01': spiral_looking_down_01,
  'spiral-looking-down-02': spiral_looking_down_02,
  'spiral-looking-down-03': spiral_looking_down_03,
};

/** A static-imported trilogy frame, keyed '<slug>-01' | '<slug>-02' | '<slug>-03'. */
export const trilogyImage = (key: string): StaticImageData | undefined =>
  TRILOGY_IMAGES[key];
