import type { MetadataRoute } from 'next';

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://ecowoods.ca';

/**
 * robots.txt — generated by Next. Explicitly welcomes general search crawlers
 * AND the major AI agents (so ChatGPT, Claude, Perplexity, Gemini etc. can read
 * and cite the site), while keeping private surfaces out of the index.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        // /api/knowledge is the public JSON corpus and is meant to be fetched.
        // /llms-full.txt and /md/ are the machine-readable editions: the whole
        // corpus in one fetch, and the clean-markdown companion of each page
        // (served at /papers/{slug}.md and friends by a rewrite in
        // next.config.js). Both are already covered by Allow: '/'. They are
        // named anyway, because robots.txt is the first file an agent reads and
        // an editions list that appears there costs one line.
        //
        // It sits under /api/, which is disallowed wholesale below, and a
        // blanket Disallow: /api/ would have hidden the one endpoint built
        // specifically for crawlers and agents to read. Allow is listed first
        // and is more specific, which is how every major crawler resolves the
        // conflict. See F-89.
        //
        // /catalogues is the field-catalogue index and /catalogues/ the PDF
        // documents themselves. Both are already covered by Allow: '/' and
        // neither sits under a disallowed prefix; they are named for the same
        // reason the editions above are — robots.txt is the first file an agent
        // reads, and a document family that appears there costs one line.
        allow: ['/', '/api/knowledge', '/api/market', '/api/estimate', '/api/health', '/api/v1', '/api/v1/', '/llms.txt', '/llms-full.txt', '/md/', '/catalogues', '/catalogues/'],
        // BOTH SPELLINGS ARE LISTED, AND THAT IS NOT REDUNDANT. robots.txt
        // matching is plain prefix matching: 'Allow: /api/v1/' does not match
        // the path '/api/v1', so the bare base URL — the one this site
        // advertises in the OpenAPI `servers` field and in /api/v1/manifest,
        // and therefore the first URL any agent requests — fell through to
        // 'Disallow: /api/'. Verified externally: a compliant fetcher asking
        // for https://ecowoods.ca/api/v1 was refused as ROBOTS_DISALLOWED
        // while https://ecowoods.ca/api/v1/pricing was served. The index of
        // the agentic API was the one endpoint agents were told to skip.
        // /api/v1/ is the public, read-only, versioned primitives API (entity,
        // services, locations, pricing, evidence, citations, OpenAPI). It is
        // meant to be fetched by agents; the wholesale Disallow: /api/ below
        // still covers everything private.
        // /docs/{contract,invoice,quote}/[id] renders a specific customer's
        // paperwork from a URL. It was never disallowed.
        disallow: ['/admin', '/mypage', '/api/', '/login', '/register', '/verify-email', '/docs/'],
      },
      // Named allow for AI crawlers — some ignore '*', so naming them removes
      // doubt. Tokens are the ones each operator actually documents:
      //   OpenAI      GPTBot (training), OAI-SearchBot (search index),
      //               ChatGPT-User (user-initiated fetch)
      //   Anthropic   ClaudeBot (crawler), Claude-User, Claude-SearchBot
      //   Google      Google-Extended (Gemini grounding; NOT "Googlebot-Extended",
      //               which is not a real token and matches nothing)
      //   Apple       Applebot-Extended
      //   Perplexity  PerplexityBot
      //   Common Crawl CCBot — the corpus most open models train on
      {
        userAgent: [
          'GPTBot', 'OAI-SearchBot', 'ChatGPT-User',
          'ClaudeBot', 'Claude-User', 'Claude-SearchBot', 'anthropic-ai', 'Claude-Web',
          'Google-Extended', 'Applebot-Extended',
          'PerplexityBot', 'Perplexity-User',
          'CCBot', 'cohere-ai', 'Meta-ExternalAgent', 'Amazonbot',
        ],
        allow: ['/', '/api/knowledge', '/api/market', '/api/estimate', '/api/health', '/api/v1', '/api/v1/', '/llms.txt', '/llms-full.txt', '/md/', '/catalogues', '/catalogues/'],
        disallow: ['/admin', '/mypage', '/api/', '/login', '/register', '/verify-email', '/docs/'],
      },
    ],
    // app/sitemap.ts exports a single default sitemap, so Next serves exactly
    // one file at /sitemap.xml. The two children below were left over from a
    // generateSitemaps() split that no longer exists — both were 404s, which
    // means every crawler that read this file was handed two dead sitemap URLs
    // and zero live ones. See audit/FINDINGS.md F-21.
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
