import type { MetadataRoute } from 'next';

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://ecowoods.ca';

/**
 * robots.txt — generated by Next. Explicitly welcomes general search crawlers
 * AND the major AI agents (so ChatGPT, Claude, Perplexity, Gemini etc. can read
 * and cite the site), while keeping private surfaces out of the index.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: ['/admin', '/mypage', '/api/', '/login', '/register', '/verify-email'],
      },
      // Named allow for AI crawlers — some ignore '*'; naming them removes doubt.
      { userAgent: ['GPTBot', 'OAI-SearchBot', 'ChatGPT-User', 'ClaudeBot', 'Claude-Web', 'anthropic-ai', 'PerplexityBot', 'Google-Extended', 'Applebot-Extended', 'CCBot'], allow: '/' },
    ],
    sitemap: [
      `${SITE_URL}/sitemap/0.xml`,
      `${SITE_URL}/sitemap/1.xml`,
    ],
    host: SITE_URL,
  };
}
