import type { MetadataRoute } from 'next';

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://ecowoods.ca';

/**
 * sitemap.xml — generated by Next. The site is a single indexable landing page;
 * listing it with a fresh lastModified and high priority tells crawlers what to
 * fetch first. Add real sub-pages here as they ship.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: SITE_URL,
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 1,
    },
  ];
}
