import type { Metadata } from 'next';
import Link from 'next/link';
import { BUSINESS_NAP } from '@ecowoods/shared/constants';
import { FINISH_OPTIONS, PATTERN_OPTIONS } from '@ecowoods/shared/ai';
import { SITE_URL } from '@/lib/seo-data';
import { PRICE_PROMISE } from '@/lib/pricing';
import { NEW_INSTALL, formatBand } from '@/content/constants/pricing';
import { buildBreadcrumbList } from '@/lib/schema/builders';
import { SchemaScript } from '@/lib/schema/components';
import { BOARD_WIDTHS, FLOOR_PRODUCTS } from '@/lib/floor-studio/catalog';
import { FEELS } from '@/lib/floor-studio/match';
import { NextStep } from '@/app/components/NextStep';
import FloorStudio from '@/app/components/floor-studio/FloorStudio';
import { illustrationImage } from '@/app/data/illustration-images';

/**
 * /floor-studio — ECOWOODS FLOOR STUDIO.
 *
 * ONE SYSTEM, FOUR DOORS, AND THIS IS THE ONE PEOPLE COME THROUGH
 *
 *   /floor-studio  discovery: a photograph, a real floor rendered into it, desire
 *   /design        the advanced configurator, already live and untouched
 *   /estimate      the professional measure and the fixed written price
 *   /pricing       the published bands
 *
 * The studio does not duplicate /design and does not replace it. /design asks a
 * person who already knows they want hardwood to specify it; the studio asks a
 * person who does not yet know what they want to SEE it. They share one
 * catalogue, one pricing function and one handoff, so a visitor moving between
 * them never feels they left the company.
 *
 * WHY THE INTERACTIVE PART IS AN ISLAND IN A SERVER PAGE
 *
 * The wow is a canvas and the canvas needs the browser. Everything around it —
 * what the studio is, which floors exist, what the bands are, what it refuses
 * to do — is server-rendered prose, because a page whose entire content appears
 * only after hydration is a page a crawler, a retrieval system and a person on
 * a bad connection all see as empty. This site has already paid for that lesson
 * once (F-160: <form> count zero on every page).
 *
 * THE COPY BELOW IS NOT FILLER. It is the machine-readable statement of what
 * Floor Studio is, which is the only way an assistant answering "can I see a
 * floor in my own room before I buy it in Toronto" can know this exists.
 */

const url = `${SITE_URL}/floor-studio`;

export const metadata: Metadata = {
  title: 'Floor Studio — see your new floor in your room',
  description:
    `Upload a photo of your room and see real ${BUSINESS_NAP.name} floors in it — species, finish, pattern and board width, with a live estimated installed range in CAD. The photo never leaves your device.`,
  alternates: { canonical: '/floor-studio', types: { 'text/markdown': '/floor-studio.md' } },
  openGraph: {
    images: [{ url: illustrationImage('og-floor-studio')?.src ?? '/illustrations/og-floor-studio.webp', width: 1200, height: 630 }],
    title: 'Ecowoods Floor Studio — see your new floor in your room',
    description:
      'A photo of your room, a real Ecowoods floor rendered into it, and a live installed range. A range, not a quote.',
    type: 'website',
    url,
  },
};

const STEPS = [
  {
    id: 'step-photo',
    title: 'Your photo, read in your browser',
    body:
      'The studio measures the light in the room, the undertone of the walls, how dark the floor that is there now reads, and where the floor plane appears to meet them. All of it runs on your own device. Nothing is uploaded and we keep nothing.',
  },
  {
    id: 'step-correct',
    title: 'You correct what we got wrong',
    body:
      'Four corners you can drag or move with the arrow keys. We never claim the boundary is certain, and we ask for the two things a photograph genuinely cannot tell us: how many square feet you are covering, and which room this is.',
  },
  {
    id: 'step-see',
    title: 'Real floors, in your room',
    body:
      'Every floor you can see is one we can supply and install. Nothing is generated by an image model, because a floor that does not exist cannot be bought. Change species, finish, pattern or board width and the room changes with it.',
  },
  {
    id: 'step-price',
    title: 'A range, then a fixed price',
    body:
      `The installed range updates as you change the floor, from the same numbers our estimator carries in the truck. ${PRICE_PROMISE} The studio hands your exact design to the estimate form — there is nothing to retype.`,
  },
];

const REFUSALS = [
  'It does not generate floors. Every board rendered into your room is a configuration this company can supply and install.',
  'It does not measure your room. A single photo with nothing of known size in it cannot give an area, so the studio asks you instead of printing a number that is quietly wrong.',
  'It does not give you a quote. The figure is an estimated installed range and it is labelled as one on every screen it appears.',
  'It does not keep your photograph. The analysis and the rendering both run in your browser; a shared design link carries the floor, never the room.',
];

export default function FloorStudioPage() {
  return (
    <div className="tlx-page">
      <SchemaScript
        schema={buildBreadcrumbList([
          { name: 'Home', url: SITE_URL },
          { name: 'Floor Studio', url },
        ])}
      />
      <SchemaScript
        schema={{
          '@context': 'https://schema.org',
          '@type': 'WebApplication',
          '@id': `${url}#app`,
          url,
          name: 'Ecowoods Floor Studio',
          applicationCategory: 'DesignApplication',
          operatingSystem: 'Any modern web browser',
          inLanguage: 'en-CA',
          isPartOf: { '@id': `${SITE_URL}/#website` },
          publisher: { '@id': `${SITE_URL}/#organization` },
          description:
            'Upload a photograph of a room and see real Ecowoods hardwood configurations rendered into it, with a live estimated installed range in Canadian dollars. Runs entirely in the browser; the photograph is not uploaded.',
          featureList: [
            'Room photograph analysis in the browser',
            'Correctable floor boundary',
            'Recommendations over installable configurations only',
            'Species, finish, pattern and board width',
            'Live estimated installed range in CAD',
            'Shareable design link',
            'Structured handoff into the free in-home measure',
          ],
          potentialAction: {
            '@type': 'QuoteAction',
            name: 'Get a fixed written price for this floor',
            target: { '@type': 'EntryPoint', urlTemplate: `${SITE_URL}/estimate#form` },
          },
        }}
      />

      <header className="tlx-hero">
        <div className="shell">
          <nav className="tlx-crumbs" aria-label="Breadcrumb">
            <Link href="/">Home</Link> <span aria-hidden="true">/</span> <span>Floor Studio</span>
          </nav>
          <h1 className="tlx-title">See your new floor in your home</h1>
          <p className="tlx-lede">
            Upload a photo of your room, or start from a floor, and see real {BUSINESS_NAP.name} hardwood
            in your own space — species, finish, pattern and board width, with a live estimated
            installed range in Canadian dollars. Design it digitally. Verify it professionally. Build
            it perfectly.
          </p>
        </div>
      </header>

      <FloorStudio />

      <section className="tlx-section" id="how" aria-label="How Floor Studio works">
        <div className="shell">
          <p className="tlx-kicker">Four steps</p>
          <h2 className="tlx-h2">How it works</h2>
          <ol className="wp-steps">
            {STEPS.map((s, i) => (
              <li key={s.id} id={s.id}>
                <strong>
                  {i + 1}. {s.title}.
                </strong>{' '}
                {s.body}
              </li>
            ))}
          </ol>
        </div>
      </section>

      <section className="tlx-section" id="floors" aria-label="The floors in Floor Studio">
        <div className="shell">
          <p className="tlx-kicker">The catalogue</p>
          <h2 className="tlx-h2">Every floor the studio can show you</h2>
          <p className="tlx-lede">
            Five species, {FINISH_OPTIONS.length} finishes, {PATTERN_OPTIONS.length} patterns and{' '}
            {BOARD_WIDTHS.length} board widths, in the combinations we actually lay. Fuming is an
            ammonia reaction with the tannin in the wood, so it is offered on oak and not on maple or
            hickory. Herringbone and chevron are cut as blocks, so they are laid at 3¼″ and 5″.
          </p>
          <ul className="wp-bullets">
            {FLOOR_PRODUCTS.map((p) => (
              <li key={p.id}>
                <strong>{p.name}</strong> — Janka {p.janka}. {p.note} Suited to {p.suitedTo.join(', ')}.
              </li>
            ))}
          </ul>
          <p>
            Board width changes how the floor looks and how far each board moves between a Toronto
            July and a Toronto February — the studio computes that from the published Wood Handbook
            coefficients, the same ones behind{' '}
            <Link href="/tools/floor-movement">the movement calculator</Link>. It does not change the
            published band.
          </p>
        </div>
      </section>

      <section className="tlx-section" id="feel" aria-label="What Floor Studio asks">
        <div className="shell">
          <p className="tlx-kicker">Feel first</p>
          <h2 className="tlx-h2">It asks how you want the room to feel, not how hard the wood is</h2>
          <p className="tlx-lede">
            Nobody outside the trade opens a renovation by asking about Janka ratings. The studio asks
            for one of these and translates it into a specification, which is our job rather than
            yours:
          </p>
          <ul className="wp-bullets">
            {FEELS.filter((f) => f.id !== 'unsure').map((f) => (
              <li key={f.id}>
                <strong>{f.label}</strong> — {f.blurb}
              </li>
            ))}
          </ul>
          <p>
            Every recommendation comes back with a match percentage and the sentences that produced
            it. A percentage with nothing under it is a number you cannot check, and it has no
            business in a decision this size.
          </p>
        </div>
      </section>

      <section className="tlx-section" id="limits" aria-label="What Floor Studio will not do">
        <div className="shell">
          <p className="tlx-kicker">Plainly</p>
          <h2 className="tlx-h2">What it will not do</h2>
          <ul className="wp-bullets">
            {REFUSALS.map((r) => (
              <li key={r}>{r}</li>
            ))}
          </ul>
          <p>
            New hardwood installation is published at {formatBand(NEW_INSTALL)}; the three bands and
            what moves a job inside them are on <Link href="/pricing">the pricing page</Link>. When you
            are ready, <Link href="/estimate">the free in-home measure</Link> is where the fixed
            written price comes from, and{' '}
            <Link href="/design">the full configurator</Link> is where the specification gets finished.
          </p>
        </div>
      </section>

      <NextStep route="/floor-studio" />
    </div>
  );
}
